application:
  title: OpenCFP
  url: http://cfp.dev
  email: contact@openconf.com
  eventurl: http://myenvent.com
  enddate: Oct. 14th, 2016
  show_submission_count: false
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: false

api:
  enabled: true

cache:
  enabled: false

database:
  host: localhost
  database: cfp_testing
  dsn: sqlite:cfp_testing
  sqlite::memory:
mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
